<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Champagne',
                'slug' => 'champagne',
                'type' => 'Champán',
                'description' => 'Champagnes franceses de distintas casas productoras, incluyendo opciones brut, rosadas y de añada.',
                'image' => 'categoria-champagne.jpg',
            ],
            [
                'name' => 'Vino tinto',
                'slug' => 'vino-tinto',
                'type' => 'Vino',
                'description' => 'Vinos tintos elaborados con uvas como Cabernet Sauvignon, Malbec, Tempranillo, Pinot Noir y otras variedades.',
                'image' => 'categoria-vino-tinto.jpg',
            ],
            [
                'name' => 'Vino blanco',
                'slug' => 'vino-blanco',
                'type' => 'Vino',
                'description' => 'Vinos blancos frescos y aromáticos elaborados con variedades como Sauvignon Blanc, Chardonnay y Pinot Grigio.',
                'image' => 'categoria-vino-blanco.jpg',
            ],
            [
                'name' => 'Vino rosado',
                'slug' => 'vino-rosado',
                'type' => 'Vino',
                'description' => 'Vinos rosados de perfil fresco, frutal y ligero, principalmente asociados con regiones como Provence.',
                'image' => 'categoria-vino-rosado.jpg',
            ],
        ];

        foreach ($categories as $categoryData) {
            Category::create($categoryData);
        }

        $categoryIds = Category::pluck('id', 'slug');

        $products = [
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Dom Pérignon Vintage 2013',
                'producer' => 'Moët & Chandon',
                'description' => 'Un champagne de gran equilibrio con notas de fruta madura y tostados.',
                'image' => 'vino-01.jpg',
                'price' => 260,
                'wine_type' => 'Blanco',
                'grape' => 'Chardonnay, Pinot Noir',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => 2013,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 8,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 95,
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Moët & Chandon Impérial Brut',
                'producer' => 'Moët & Chandon',
                'description' => 'El champagne más icónico del mundo, vibrante y generoso.',
                'image' => 'vino-02.jpg',
                'price' => 65,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Meunier, Chardonnay',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 20,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 90,
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Veuve Clicquot Yellow Label',
                'producer' => 'Veuve Clicquot',
                'description' => 'Conocido por su estructura y frescura, con predominio de Pinot Noir.',
                'image' => 'vino-03.jpg',
                'price' => 65,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 18,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 90,
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Krug Grande Cuvée 171ème Édition',
                'producer' => 'Krug',
                'description' => 'Un blend de más de 120 vinos de diferentes años; máxima complejidad.',
                'image' => 'vino-04.jpg',
                'price' => 240,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 6,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 96,
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Louis Roederer Cristal 2014',
                'producer' => 'Louis Roederer',
                'description' => 'Creado originalmente para el Zar Alejandro II; puro y preciso.',
                'image' => 'vino-05.jpg',
                'price' => 350,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => 2014,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 5,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 97,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Ruinart Blanc de Blancs',
                'producer' => 'Ruinart',
                'description' => 'La expresión máxima de la uva Chardonnay; elegante y luminoso.',
                'image' => 'vino-06.jpg',
                'price' => 95,
                'wine_type' => 'Blanco',
                'grape' => '100% Chardonnay',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 12,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Laurent-Perrier Cuvée Rosé',
                'producer' => 'Laurent-Perrier',
                'description' => 'Famoso por su frescura y notas intensas de frutos rojos.',
                'image' => 'vino-07.jpg',
                'price' => 105,
                'wine_type' => 'Rosado',
                'grape' => '100% Pinot Noir',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 10,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Bollinger Special Cuvée',
                'producer' => 'Bollinger',
                'description' => 'Un champagne con mucho cuerpo, fermentado parcialmente en barrica.',
                'image' => 'vino-08.jpg',
                'price' => 75,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 15,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 91,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Taittinger Comtes de Champagne 2012',
                'producer' => 'Taittinger',
                'description' => 'Elaborado solo en años excepcionales usando uvas Grand Cru.',
                'image' => 'vino-09.jpg',
                'price' => 210,
                'wine_type' => 'Blanco',
                'grape' => '100% Chardonnay',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => 2012,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 7,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 95,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Perrier-Jouët Belle Epoque 2014',
                'producer' => 'Perrier-Jouët',
                'description' => 'Una obra de arte embotellada con notas de flores blancas.',
                'image' => 'vino-10.jpg',
                'price' => 200,
                'wine_type' => 'Blanco',
                'grape' => 'Chardonnay, Pinot Noir, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => 2014,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 6,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 94,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Pol Roger Sir Winston Churchill 2015',
                'producer' => 'Pol Roger',
                'description' => 'Robusto, maduro y con una estructura excepcional.',
                'image' => 'vino-11.jpg',
                'price' => 310,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => 2015,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 4,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 96,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Billecart-Salmon Brut Rosé',
                'producer' => 'Billecart-Salmon',
                'description' => 'Considerado uno de los mejores rosados por su finura.',
                'image' => 'vino-12.jpg',
                'price' => 90,
                'wine_type' => 'Rosado',
                'grape' => 'Chardonnay, Pinot Noir, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 13,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'G.H. Mumm Grand Cordon',
                'producer' => 'G.H. Mumm',
                'description' => 'Distinguido por su frescura frutal y su cinta roja en la botella.',
                'image' => 'vino-13.jpg',
                'price' => 50,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 22,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 88,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Charles Heidsieck Brut Réserve',
                'producer' => 'Charles Heidsieck',
                'description' => 'Envejecido por mucho tiempo para obtener notas de brioche.',
                'image' => 'vino-14.jpg',
                'price' => 68,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Chardonnay, Meunier',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 16,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 91,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['champagne'],
                'name' => 'Piper-Heidsieck Cuvée Brut',
                'producer' => 'Piper-Heidsieck',
                'description' => 'Un champagne estructurado y lleno de notas frutales cítricas.',
                'image' => 'vino-15.jpg',
                'price' => 48,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Noir, Meunier, Chardonnay',
                'country' => 'Francia',
                'region' => 'Champagne',
                'appellation' => 'AOC Champagne',
                'vintage_year' => null,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'stock' => 24,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 88,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Casillero del Diablo Reserva',
                'producer' => 'Concha y Toro',
                'description' => 'Vino chileno icónico con notas de vainilla y bayas negras.',
                'image' => 'vino-16.jpg',
                'price' => 12,
                'wine_type' => 'Tinto',
                'grape' => 'Cabernet Sauvignon',
                'country' => 'Chile',
                'region' => 'Valle Central',
                'appellation' => 'D.O. Valle Central',
                'vintage_year' => 2021,
                'volume_ml' => 750,
                'alcohol_percentage' => 13.5,
                'stock' => 40,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 85,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Catena Zapata Malbec Argentino',
                'producer' => 'Bodega Catena Zapata',
                'description' => 'Un referente del Malbec de altura, complejo y elegante.',
                'image' => 'vino-17.jpg',
                'price' => 110,
                'wine_type' => 'Tinto',
                'grape' => 'Malbec',
                'country' => 'Argentina',
                'region' => 'Mendoza',
                'appellation' => 'Valle de Uco',
                'vintage_year' => 2020,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'stock' => 12,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 94,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Marqués de Riscal Reserva',
                'producer' => 'Herederos del Marqués de Riscal',
                'description' => 'Clásico de Rioja con crianza en roble americano, notas de regaliz.',
                'image' => 'vino-18.jpg',
                'price' => 25,
                'wine_type' => 'Tinto',
                'grape' => 'Tempranillo, Graciano',
                'country' => 'España',
                'region' => 'La Rioja',
                'appellation' => 'DOCa Rioja',
                'vintage_year' => 2018,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'stock' => 25,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 89,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-blanco'],
                'name' => 'Santa Margherita Pinot Grigio',
                'producer' => 'Santa Margherita',
                'description' => 'Vino blanco seco, fresco y limpio, un éxito internacional.',
                'image' => 'vino-19.jpg',
                'price' => 22,
                'wine_type' => 'Blanco',
                'grape' => 'Pinot Grigio',
                'country' => 'Italia',
                'region' => 'Alto Adige',
                'appellation' => 'DOC Valdadige',
                'vintage_year' => 2022,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 28,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 87,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-blanco'],
                'name' => 'Cloudy Bay Sauvignon Blanc',
                'producer' => 'Cloudy Bay (LVMH)',
                'description' => 'El vino que puso a Nueva Zelanda en el mapa por su frescura cítrica.',
                'image' => 'vino-20.jpg',
                'price' => 35,
                'wine_type' => 'Blanco',
                'grape' => 'Sauvignon Blanc',
                'country' => 'Nueva Zelanda',
                'region' => 'Marlborough',
                'appellation' => 'Marlborough',
                'vintage_year' => 2023,
                'volume_ml' => 750,
                'alcohol_percentage' => 13.0,
                'stock' => 20,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 90,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Sassicaia Tenuta San Guido',
                'producer' => 'Tenuta San Guido',
                'description' => 'El Super Toscano más famoso, con gran potencial de guarda.',
                'image' => 'vino-21.jpg',
                'price' => 350,
                'wine_type' => 'Tinto',
                'grape' => 'Cabernet Sauvignon, Cabernet Franc',
                'country' => 'Italia',
                'region' => 'Toscana',
                'appellation' => 'Bolgheri Sassicaia DOC',
                'vintage_year' => 2019,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'stock' => 5,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 96,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Caymus Napa Valley Cabernet',
                'producer' => 'Caymus Vineyards',
                'description' => 'Vino denso, de color oscuro y con taninos aterciopelados.',
                'image' => 'vino-22.jpg',
                'price' => 90,
                'wine_type' => 'Tinto',
                'grape' => 'Cabernet Sauvignon',
                'country' => 'EE.UU.',
                'region' => 'California',
                'appellation' => 'Napa Valley AVA',
                'vintage_year' => 2021,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.6,
                'stock' => 10,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 91,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-rosado'],
                'name' => 'Miraval Côtes de Provence',
                'producer' => 'Château Miraval',
                'description' => 'El rosado más famoso de Francia, fresco con notas de melocotón.',
                'image' => 'vino-23.jpg',
                'price' => 28,
                'wine_type' => 'Rosado',
                'grape' => 'Grenache, Cinsault, Rolle',
                'country' => 'Francia',
                'region' => 'Provence',
                'appellation' => 'AOC Côtes de Provence',
                'vintage_year' => 2022,
                'volume_ml' => 750,
                'alcohol_percentage' => 13.0,
                'stock' => 22,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 88,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Penfolds Bin 389',
                'producer' => 'Penfolds',
                'description' => 'Conocido como el Baby Grange, una mezcla potente y rica.',
                'image' => 'vino-24.jpg',
                'price' => 80,
                'wine_type' => 'Tinto',
                'grape' => 'Cabernet Sauvignon, Shiraz',
                'country' => 'Australia',
                'region' => 'South Australia',
                'appellation' => 'South Australia',
                'vintage_year' => 2019,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.5,
                'stock' => 11,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Vega Sicilia Único',
                'producer' => 'Bodegas Vega Sicilia',
                'description' => 'Considerado el mejor vino de España, con una guarda larguísima.',
                'image' => 'vino-25.jpg',
                'price' => 450,
                'wine_type' => 'Tinto',
                'grape' => 'Tempranillo, Cabernet Sauvignon',
                'country' => 'España',
                'region' => 'Castilla y León',
                'appellation' => 'DO Ribera del Duero',
                'vintage_year' => 2012,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'stock' => 3,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 98,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-blanco'],
                'name' => 'Kim Crawford Sauvignon Blanc',
                'producer' => 'Kim Crawford Wines',
                'description' => 'Explosión de frutas tropicales y acidez vibrante.',
                'image' => 'vino-26.jpg',
                'price' => 18,
                'wine_type' => 'Blanco',
                'grape' => 'Sauvignon Blanc',
                'country' => 'Nueva Zelanda',
                'region' => 'Marlborough',
                'appellation' => 'Marlborough',
                'vintage_year' => 2023,
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'stock' => 35,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 86,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Château Mouton Rothschild',
                'producer' => 'Baron Philippe de Rothschild',
                'description' => 'Un Premier Cru de Burdeos con etiquetas de artistas famosos.',
                'image' => 'vino-27.jpg',
                'price' => 750,
                'wine_type' => 'Tinto',
                'grape' => 'Cabernet Sauvignon, Merlot',
                'country' => 'Francia',
                'region' => 'Burdeos',
                'appellation' => 'AOC Pauillac',
                'vintage_year' => 2017,
                'volume_ml' => 750,
                'alcohol_percentage' => 13.5,
                'stock' => 2,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 97,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Errazuriz Don Maximiano',
                'producer' => 'Viña Errázuriz',
                'description' => 'Vino de estructura firme que representa lo mejor del Valle de Aconcagua.',
                'image' => 'vino-28.jpg',
                'price' => 100,
                'wine_type' => 'Tinto',
                'grape' => 'Cabernet Sauvignon, Syrah',
                'country' => 'Chile',
                'region' => 'Valle de Aconcagua',
                'appellation' => 'Aconcagua Valley',
                'vintage_year' => 2018,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'stock' => 8,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 92,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-rosado'],
                'name' => 'Whispering Angel',
                'producer' => "Caves d'Esclans",
                'description' => 'El rosado de lujo que inició la tendencia mundial de Provence.',
                'image' => 'vino-29.jpg',
                'price' => 25,
                'wine_type' => 'Rosado',
                'grape' => 'Grenache, Rolle, Cinsault',
                'country' => 'Francia',
                'region' => 'Provence',
                'appellation' => 'AOC Côtes de Provence',
                'vintage_year' => 2022,
                'volume_ml' => 750,
                'alcohol_percentage' => 13.0,
                'stock' => 24,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 88,
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['vino-tinto'],
                'name' => 'Opus One',
                'producer' => 'Opus One Winery',
                'description' => 'La alianza entre Robert Mondavi y el Barón Philippe de Rothschild.',
                'image' => 'vino-30.jpg',
                'price' => 400,
                'wine_type' => 'Tinto',
                'grape' => 'Bordeaux Blend',
                'country' => 'EE.UU.',
                'region' => 'California',
                'appellation' => 'Napa Valley AVA',
                'vintage_year' => 2018,
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'stock' => 4,
                'condition' => 'Excelente',
                'rating_source' => 'Catálogo',
                'rating_score' => 96,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $productData) {
            Product::create(array_merge($productData, [
                'slug' => Str::slug($productData['name']),
            ]));
        }
    }
}